---
- name: install boundary controller
  hosts: all
  serial: 1
  become: true

  vars:
    BOUNDARY_VERSION: "0.1.2"
    BOUNDARY_LICENSE: ""
    CLUSTER_NAME: "Boundary-Example"
    NODE_NAME: "Boundary-Controller"
    ADDR: "127.0.0.1"

  tasks:

  - name: install epel-release
    yum:
      name: epel-release
      state: present

  - name: install common packages
    yum:
      name:
        - unzip
        - vim
        - jq
      state: present

  - name: disable selinux
    selinux:
      policy: targeted
      state: permissive

  - name: enable docker repo
    yum_repository:
      name: docker-ce
      description: Docker CE Repository
      baseurl: "https://download.docker.com/linux/centos/9/$basearch/stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: preinstall containerd
    yum:
      name: containerd.io
      update_cache: true
      state: present

  - name: install docker
    yum:
      name: "docker-ce"
      update_cache: true
      state: present
    register: yum_docker_install
    until: yum_docker_install is success
    retries: 3
    delay: 60

  - name: enable docker
    systemd:
      name: docker
      state: started
      enabled: true

  - name: ensure docker group exists
    group:
      name: docker
      state: present

  - name: download binary
    unarchive:
      src: "https://releases.hashicorp.com/boundary/{{ BOUNDARY_VERSION }}/boundary_{{ BOUNDARY_VERSION }}_linux_amd64.zip"
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: set cap_ipc_lock=+ep
    capabilities:
      path: /usr/local/bin/boundary
      capability: cap_ipc_lock=+ep
      state: present

  - name: Add the system user 'boundary'
    user:
      name: boundary
      home: /etc/boundary.d
      shell: /bin/false
      system: yes

  - name: create config directory
    file: 
      path: /etc/boundary.d/
      state: directory
      recurse: yes
      owner: boundary
      group: boundary

  - name: Add user boundary' to the 'docker' group
    user:
      name: boundary
      group: docker

  - name: configure env file
    template:
      src: ./files/boundary-env.conf.j2
      dest: /etc/boundary.d/env.conf
      mode: 0640
      owner: boundary
      group: boundary

  - name: configure systemd
    copy:
      src: ./files/boundary-controller.service
      dest: /etc/systemd/system/boundary.service

  - name: start boundary controller
    systemd:
      name: boundary.service
      state: restarted
      enabled: yes
      daemon_reload: yes