---
- name: install pre-requisites
  ansible.builtin.import_playbook: prereqs.yml

- name: install boundary controller
  hosts: all
  serial: 1
  become: true

  vars:
    BOUNDARY_VERSION: "0.1.2"
    BOUNDARY_LICENSE: ""
    CLUSTER_NAME: "Boundary-Example"
    NODE_NAME: "Boundary-Controller"
    ADDR: "127.0.0.1"

  tasks:

  - name: create tls directory
    file: 
      path: /etc/boundary.d/tls/
      state: directory
      recurse: yes
      owner: boundary
      group: boundary

  - name: create tls cert file
    copy:
      src: ./files/boundary.crt
      dest: /etc/boundary.d/tls/boundary-cert.pem
      mode: 0640
      owner: boundary
      group: boundary

  - name: create tls key file
    copy:
      src: ./files/boundary.key
      dest: /etc/boundary.d/tls/boundary-key.pem
      mode: 0640
      owner: boundary
      group: boundary

  - name: create tls client ca file
    copy:
      src: ./files/boundary.ca
      dest: /etc/boundary.d/tls/boundary-ca.pem
      mode: 0640
      owner: boundary
      group: boundary

  - name: create logging directory
    file: 
      path: /var/log/boundary
      state: directory
      recurse: yes
      owner: boundary
      group: boundary

  - name: configure env file
    template:
      src: ./files/boundary-env.conf.j2
      dest: /etc/boundary.d/boundary.env
      mode: 0640
      owner: boundary
      group: boundary

  - name: configure controller
    template:
      src: ./files/boundary-controller.hcl.j2
      dest: /etc/boundary.d/controller.hcl
      mode: 0640
      owner: boundary
      group: boundary

  - name: configure systemd
    copy:
      src: ./files/boundary-controller.service
      dest: /etc/systemd/system/boundary.service

  - name: start boundary controller
    systemd:
      name: boundary.service
      state: restarted
      enabled: yes
      daemon_reload: yes